plug:
  network_id: balance.tutorial
  max_block_size: 1000
  runner:
    proposal_window: PT5S
  registry:
    plugins:
    - plugin.BalancePlugin
  storage:
    class: plug.storage.sqlite.SqliteStorage
    path: db.sqlite
    store_n_states: 10